version: '3.8'
services:

  redis:
    image: redis
    environment:
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      network:
        ipv4_address: 10.5.0.2


  highload-service:
    image: storage-container
    container_name: service-container
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 10.5.0.4
    ports:
      - ${SERVER_SWAGGER_PORT}:${SERVER_PORT}

  highload-client:
    image: client-container
    command: get ab
    container_name: client-container
    networks:
      network:
        ipv4_address: 10.5.0.3

networks:
      network:
        driver: bridge
        ipam:
          config:
            - subnet: 10.5.0.0/16
              gateway: 10.5.0.1