version: '3.8'
services:

  redis-master:
    image: redis
    container_name: redis-master
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6380
    networks:
      network:
        ipv4_address: 172.28.1.4
    ports:
      - "6380:6380"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  redis-replica0:
    image: redis
    container_name: redis-replica0
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6381 --slaveof 172.28.1.4 6380 --read-only yes
    networks:
      network:
        ipv4_address: 172.28.1.5
    ports:
      - "6381:6381"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  redis-replica1:
    image: redis
    container_name: redis-replica1
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6382 --slaveof 172.28.1.4 6380 --read-only yes
    networks:
      network:
        ipv4_address: 172.28.1.6
    ports:
      - "6382:6382"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  highload-service:
    image: storage-container
    container_name: service-container
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 10.5.0.4
    ports:
      - ${SERVER_SWAGGER_PORT}:${SERVER_PORT}

  highload-client:
    image: client-container
    command: get ab
    container_name: client-container
    networks:
      network:
        ipv4_address: 10.5.0.3

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
