version: '3.8'
services:

  redis:
    image: redis
    environment:
      REDIS_USERNAME: default
      REDIS_PASSWORD: redispw
    ports:
      - "6379:6379"
    networks:
      network:
        ipv4_address: 10.5.0.2


  highload-service:
    image: server
    container_name: service-container
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 10.5.0.4
    ports:
      - "5050:8080"

  highload-client:
    image: client
    command: get ab
    container_name: client-container
    networks:
      network:
        ipv4_address: 10.5.0.3

networks:
      network:
        driver: bridge
        ipam:
          config:
            - subnet: 10.5.0.0/16
              gateway: 10.5.0.1